apiVersion: v1
kind: Namespace
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-prod-secret
  namespace: mysql
type: kubernetes.io/basic-auth
stringData:
  password: m!srv156
