apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dev
spec:
  selector:
    matchLabels:
      app: mysql-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dev
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-dev-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-dev
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "125m"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-dev-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dev-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: mysql-dev
