apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-prod
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-prod
    spec:
      nodeSelector:
        disktype: ssd1
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-prod
        resources:
          requests:
            memory: "512Mi"
            cpu: "700m"
          limits:
            memory: "512Mi"
            cpu: "700m"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-prod-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-prod-service
  namespace: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-prod
