apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dev-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
