apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmongo
  namespace: rocketmongo
spec:
  serviceName: rocketmongo
  replicas: 3
  selector:
    matchLabels:
      app: rocketmongo
  template:
    metadata:
      labels:
        app: rocketmongo
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: rocketmongo
          image: mongo:4.0
          command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0  
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.25"
            requests:
              cpu: "0.25"
              memory: "128Mi"    
          volumeMounts:
          - name: mongo-volumes
            mountPath: /data/dbs
  volumeClaimTemplates:
  - metadata:
      name: mongo-volumes
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmongo
  namespace: rocketmongo
  labels:
    app: rocketmongo
spec:
  selector:
    app: rocketmongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
