apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server
  namespace: rocketmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      nodeSelector:
        rocket: permit
      containers:
        - name: rocketchat-server
          image: rocketchat/rocket.chat:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://rocketmongo-0.rocketmongo:27017/rocketchat
            - name: MONGO_OPLOG_URL
              value: mongodb://rocketmongo-0.rocketmongo:27017/local?replSet=rs0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "200m"
            requests:
              cpu: "200m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-server
  namespace: rocketmongo
spec:
  selector:
    app: rocketchat-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
