apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-rocketmongo-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

