apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volumes-0
  namespace: rocketmongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dbs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volumes-rocketmongo-0
  namespace: rocketmongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volumes-1
  namespace: rocketmongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dbs1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volumes-rocketmongo-1
  namespace: rocketmongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volumes-2
  namespace: rocketmongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dbs2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volumes-rocketmongo-2
  namespace: rocketmongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

