apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: dev-range
      protocol: layer2
      addresses:
      - 192.168.88.191-192.168.88.220
    - name: prod-range
      protocol: layer2
      addresses:
      - 10.84.1.150-10.84.1.190
      auto-assign: false
